version: 0.2
phases:
  install:
    commands:
      - curl -Lo /tmp/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.50.9/terragrunt_linux_amd64
      - chmod +x /tmp/terragrunt
      - sudo mv /tmp/terragrunt /usr/local/bin/
      - curl -Lo /tmp/terraform.zip https://releases.hashicorp.com/terraform/1.6.4/terraform_1.6.4_linux_amd64.zip
      - unzip -o /tmp/terraform.zip -d /usr/local/bin
      - rm /tmp/terraform.zip
  pre_build:
    commands:
      - echo Terraform Running in QA Env..
  build:
    commands:
      - echo Terragrunt Plan Started `date`
      - ls -ltra
      - cd infra-live/qa
      - pwd
      - terragrunt -v
      - terraform -v
  post_build:
    commands:
      - echo Build completed on `date`