version: 0.2
phases:
  install:
    commands:
      - curl -Lo /tmp/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.50.9/terragrunt_linux_amd64
      - chmod +x /tmp/terragrunt
      - sudo mv /tmp/terragrunt /usr/local/bin/
  pre_build:
    commands:
      - echo Terraform Running in QA Env..
  build:
    commands:
      - echo Terragrunt Plan Started `date`
      - terragrunt run-all plan
  post_build:
    commands:
      - echo Build completed on `date`