# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.25"
    }
  }
}
provider "aws" {
  region              = "us-east-1"
  profile = "default"
  allowed_account_ids = ["521784597423"]
}
